Repository torchbox/django-pattern-library, pull requests merged in 2022-01, with the labels that each got.

#167 Add support for is_pattern_library context variable. Fix #156
  docs/guides/customizing-template-rendering.md
  docs/reference/api.md
  pattern_library/__init__.py
  tests/templates/patterns/atoms/sprites/sprites.html
  tests/tests/test_context_modifiers.py
Labels: enhancement, status: Needs review

#177 Fix LGTM warning about redefined variable
  pattern_library/utils.py
Labels: enhancement

#164 Add support for Django 4.0
  .github/workflows/ci.yml
  pyproject.toml
  tox.ini
Labels: enhancement, django

#178 Add VS Code devcontainer config
  .devcontainer/devcontainer.json
  .github/workflows/ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  README.md
  docker-compose.yml
  docs/getting-started.md
  docs/index.md
  mkdocs.yml
  tests/urls.py
Labels: enhancement

#184 Update docs for image placeholders to use Unsplash. Fix #7
  docs/guides/overriding-template-tags.md
  docs/recipes/image-include.md
  docs/recipes/image-lazyload.md
Labels: documentation, enhancement

#169 Feature: Allow `yml` extension
  CHANGELOG.md
  docs/getting-started.md
  docs/reference/api.md
  pattern_library/utils.py
  tests/templates/patterns/atoms/test_atom_yml/test_atom_yml.html
  tests/templates/patterns/atoms/test_atom_yml/test_atom_yml.yml
  tests/tests/test_utils.py
Labels: enhancement

#188 Fix #166, making sure we always cast raw tag override values to string
  pattern_library/monkey_utils.py
  tests/templates/patterns/atoms/tags_test_atom/tags_test_atom.yaml
Labels: enhancement, django
